### ISSUE TITLE
Make telegram-rs buildable on stable

### ISSUE THREAD

**Issue by hcpl** [mehcode/telegram-rs#3]
There are 3 unstable features used in this library. Ways to get around them:
- Builtin 128-bit types can be replaced using [`extprim::i128::i128`](https://docs.rs/extprim/1.4.0/extprim/i128/struct.i128.html) => drops `#![feature(i128_type)]`;
- `#id` attributes on generated structs can use string representation of id => drops `#![feature(attr_literals)]`;
- `#![feature(concat_idents)]` is not used at all (removing it and rebuilding the example was successful, even when two other features are enabled).

**Comment by mehcode** [comment]
Thanks for the contributions @hcpl 

I have this project in the back burner right now because of some work commitments but I'll be back to it in the next couple weeks or so. My next step was going to be:
 - Get a deserialize implementation working so we can deserialize the response here: https://github.com/mehcode/telegram-rs/blob/master/examples/create_auth_key/src/main.rs#L78
 - Upgrade serde and hyper
 - Transform _methods_ into functions. Something like:

```rust
impl Connection {
fn req_pq(&self, nonce: i128) -> Future<ResPQ> {
  // [...] construct a buffer (see example)

 // The .request takes care of the 4-5 common lines of setting up a hyper request
  return self.request(&buffer).then(|resp_buffer| {
    return resp_buffer.deserialize()
  })
}
}
```

My thoughts are we'd have a `Connection` struct that deals with raw access via the protocol and a `Client` struct that has high-level methods on it. Really rough thoughts as I haven't gotten too far into this.

If you want to jump on anything, be my guest. I'll help where I can until I have time to dive back in.

**Comment by hcpl** [comment]
My immediate goal is to stabilize `telegram-rs` and have `telegram`, `telegram_derive` and `telegram_codegen` 0.2.0 (because of breaking changes already in master) released as soon as possible so that it would be easier to make changes and more difficult to break public API. So don't worry, this hopefully won't stray too far from your initial development path.

Regarding your next step:
- Work in progress here, though nothing major has been achieved yet;
- I guess this should be easy, will try it out;
- Perhaps I'll deal with with `telegram_codegen` bits after implementing deserialization.

Thanks for the suggestion @mehcode!

**Comment by mehcode** [comment]
@hcpl That all sounds good. I can be available on Mozilla IRC if you want to chat. I'm `mehcode` there as well. Perhaps [#telegram](https://kiwiirc.com/client/irc.mozilla.org/#telegram)?

**Comment by hcpl** [comment]
If setting up a new channel is not very troublesome then it should be fine.

I'm `hcpl` there.

**Comment by mehcode** [comment]
@hcpl Yep. I created and set it up.

**Comment by mehcode** [comment]
@hcpl Bad timing. Sorry about that. I got distracted with life for a while there. Most of the time I'll be available. I have IRC Cloud on my phone so it pings me if you mention me.

**Comment by hcpl** [comment]
@mehcode Ah, I was setting up ZNC, so my bad here too. And best wishes for you to resolve life issues!
